site_name = "Singtober"
description = "Vous connaissez Inktober ? Bienvenue dans Singtober.\nEn partant des mêmes prompts, on est partis pour un mois de petits extraits de chanson qui contiennent le prompt.\nOn s'ajoute un petit défi : pas plus de 30 min pour enregistrer un morceau.\nPar contre, ça sera très probablement du #NoFilter 😅"
copyright = "CC BY-NC-SA"
author = "galadrieve"
locale = "fr-fr"
timezone = "Europe/Paris"
repository_url = "https://github.com/galadrieve/singtober"
colors = [ "#336699", "#669933", "#993366", "#996633", "#663399", "#339966" ]
index_colors = [ "#336699", "#663399" ]
logo = "android-chrome-512x512.png"
title_ttf_font = "Open Sans"
body_ttf_font = "Carlito"
extra_css = [ "static/singtober.css" ]

[[icon_links]]
rel = "icon"
type = "image/png"
sizes = "32x32"
href = "favicon-32x32.png"

[[icon_links]]
rel = "icon"
type = "image/png"
sizes = "16x16"
href = "favicon-16x16.png"

[[icon_links]]
rel = "apple-touch-icon"
sizes = "180x180"
href = "apple-touch-icon.png"

[[icon_links]]
rel = "manifest"
href = "site.webmanifest"

[cms_config.backend]
name = "github"
repo = "galadrieve/singtober"
